name: MultiProtocol
api: 3.0.0
version: 1.2
main: multiprotocol\MultiProtocol
description: Allows players with different versions to join.
website: https://github.com/IceCruelStuff/MultiProtocol
load: STARTUP
